kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ocean-network-client.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ocean-network-client.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ocean-network-client.name" . }}
    namespace: {{ include "ocean-network-client.namespace" . }}