apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ocean-network-client.name" . }}
  namespace: {{ include "ocean-network-client.namespace" . }}
spec:
  selector:
    matchLabels:
      {{- include "ocean-network-client.ds.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocean-network-client.ds.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: shared-data
          emptyDir: {}
      serviceAccountName: {{ include "ocean-network-client.name" . }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: netflowd
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          securityContext:
            privileged: true
            capabilities:
              drop: ["all"]
              add: [ "NET_ADMIN", "SYS_ADMIN"] # bpf need SYS_ADMIN network netlink need NET_ADMIN
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: [ "/bin/bash","-c" ]
          args: [ "mount | grep '/sys/fs/bpf type bpf' ||  mount bpffs /sys/fs/bpf -t bpf ; cd /home ;  set -m ; exec /opt/spotinst/netflow/bin/netflowd  2>> /var/log/spotnet.log" ]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: shared-data
              mountPath: /home
          env:
            - name: REPORT_INTERVAL
              value: "60"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SPOTINST_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "ocean-network-client.secretName" . }}
                  key: token
                  optional: true
            - name: SPOTINST_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: {{ include "ocean-network-client.secretName" . }}
                  key: account
                  optional: true
            - name: SPOTINST_TOKEN_LEGACY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocean-network-client.configMapName" . }}
                  key: spotinst.token
                  optional: true
            - name: SPOTINST_ACCOUNT_LEGACY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocean-network-client.configMapName" . }}
                  key: spotinst.account
                  optional: true
            - name: CLUSTER_IDENTIFIER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "ocean-network-client.configMapName" . }}
                  key: spotinst.cluster-identifier
                  optional: true
